version: '3'
services:
  db:
    image: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/julaurai

  backend:
    build: .
    volumes:
      - ~/Project/stud_projects/in_progress/node_app/backend:/home/node
    ports:
      - "3000:3000"
    command: "npm install"
    command: "npm run dev"

volumes:
  backend:
