version: '3'
services:
  db:
    image: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/julaurai

  backend:
    build: 'backend/.'
    volumes:
      - ~/Project/stud_projects/in_progress/node_app/backend:/home/node
    ports:
      - "5000:5000"
    command: "npm install"
    command: "npm run dev"
  
  front:
    build: 'front/.'
    volumes:
      - ~/Project/stud_projects/in_progress/node_app/front:/app
    ports:
      - "3000:3000"
    command: "npm install"
    command: "npm start"

volumes:
  backend:
  front:
